# NumPy (Numerical Python)

- NumPy (Numerical Python) is a powerful library for numerical computing in Python.
- It provides multi-dimensional arrays and mathematical functions for operations on these arrays.
- NumPy arrays are much faster and more memory-efficient than Python lists.

In [1]:
import numpy as np

arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))


[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
# 2d array
arr2D = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2D)
print(arr2D.shape)  # (rows, columns)
print(arr2D.size)   # Total number of elements
print(arr2D.ndim)   # Number of dimensions


[[1 2 3]
 [4 5 6]]
(2, 3)
6
2


In [4]:
# Special NumPy Arrays
zeros = np.zeros((3,3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [5]:
ones = np.ones((2, 4))  # 2 rows, 4 columns filled with 1s
print(ones)


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [6]:
identity = np.eye(4)  # 4x4 identity matrix
print(identity)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [7]:
random_array = np.random.rand(3, 3)  # 3x3 matrix with random values
print(random_array)


[[0.87021679 0.67904293 0.41816887]
 [0.89543298 0.0818423  0.3956592 ]
 [0.17983961 0.70303087 0.85432066]]


In [10]:
# Accessing elements (Indexing and slicing)
arr = np.array([10, 20, 30, 40, 50])
print(arr[0])  # First element
print(arr[-1]) # Last element

arr2D = np.array([[10, 20, 30], [40, 50, 60]])
print(arr2D[1, 2])  # Second row, third column (60)

arr = np.array([10, 20, 30, 40, 50])
print(arr[1:4])  # Elements from index 1 to 3


10
50
60
[20 30 40]


In [12]:
# NumPy operations
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

print(arr1 + arr2)  # [5 7 9]
print(arr1 * arr2)  # [4 10 18]
print(arr1 ** 2)    # [1 4 9]

arr = np.array([10, 20, 30, 40, 50])
print(np.sum(arr))      # Sum of all elements
print(np.mean(arr))     # Mean (average)
print(np.max(arr))      # Maximum value
print(np.min(arr))      # Minimum value
print(np.std(arr))      # Standard deviation


[5 7 9]
[ 4 10 18]
[1 4 9]
150
30.0
50
10
14.142135623730951


In [13]:
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped = arr.reshape(2, 3)  # Converts 1D array into 2D (2 rows, 3 columns)
print(reshaped)


[[1 2 3]
 [4 5 6]]


In [ ]:
# Pandas

Pandas is a Python library that provides fast, flexible, and expressive data structures designed to work with structured (tables, spreadsheets) and semi-structured data.

In [14]:
#A Series is like a NumPy array, but with labels (index).
import pandas as pd

data = [10, 20, 30, 40]
series = pd.Series(data)

print(series)


0    10
1    20
2    30
3    40
dtype: int64


In [15]:
students = pd.Series([90, 85, 88], index=['Alice', 'Bob', 'Charlie'])
print(students)


Alice      90
Bob        85
Charlie    88
dtype: int64


# Dataframe (2D Data)
A DataFrame is like a table or spreadsheet with rows and columns.

In [16]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 22],
    'Score': [90, 85, 88]
}

df = pd.DataFrame(data)
print(df)


      Name  Age  Score
0    Alice   25     90
1      Bob   30     85
2  Charlie   22     88
